server:
  port: 8082


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: game10122
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

welcome:
  message: Welcome to Developer!!
